# Data structures in Python

# Numbers

In [1]:
a=5
print(type(a))
a=12.5
print(type(a))
a=10+5j
print(type(a))

<class 'int'>
<class 'float'>
<class 'complex'>


In [2]:
import math

In [3]:
print(math.sqrt(4))
print(math.floor(10.7))
print(math.ceil(10.7))
print(math.pow(2,3))
print(math.factorial(6))
#print(round(math.pi,0))
print(math.pi)
print(round(math.pi,2))

2.0
10
11
8.0
720
3.141592653589793
3.14


In [4]:
area_of_circle=math.pi*10*10
print(area_of_circle)

314.1592653589793


In [5]:
import numpy
?numpy.sqrt

# Strings


In [32]:
my_string = 'Hello world'
print(my_string)

print()

"""
this is 
a comment"""

my_string = """Python is a programming language.
Python is interesting.
this is it."""
print(my_string)


Hello world

Python is a programming language.
Python is interesting.
this is it.


In [4]:
#slicing
my_string = "Python is a programming language. Python is interesting."
print(my_string[0])
print(my_string[-3])
                
#[inclusive:exclusive]
print(my_string[3:10])
print(my_string[:25])
print(my_string[25:])
print(my_string[:])
#print(my_string[54])
print(len(my_string))
print(my_string[5:8],my_string[10])

P
n
hon is 
Python is a programming l
anguage. Python is interesting.
Python is a programming language. Python is interesting.
56
n i a


In [26]:
my_string.split(sep=" ")

['Python',
 'is',
 'a',
 'programming',
 'language.',
 'Python',
 'is',
 'interesting.']

In [12]:
#strings are immutable
my_string = my_string.replace("i","B")
print(my_string)

Python Bs a programmNg language. Python Bs NterestNg.


In [28]:
list(my_string)

['P',
 'y',
 't',
 'h',
 'o',
 'n',
 ' ',
 'i',
 's',
 ' ',
 'a',
 ' ',
 'p',
 'r',
 'o',
 'g',
 'r',
 'a',
 'm',
 'm',
 'i',
 'n',
 'g',
 ' ',
 'l',
 'a',
 'n',
 'g',
 'u',
 'a',
 'g',
 'e',
 '.',
 ' ',
 'P',
 'y',
 't',
 'h',
 'o',
 'n',
 ' ',
 'i',
 's',
 ' ',
 'i',
 'n',
 't',
 'e',
 'r',
 'e',
 's',
 't',
 'i',
 'n',
 'g',
 '.']

In [11]:
my_string=my_string.replace("in","N")
print(my_string)

Python is a programmNg language. Python is NterestNg.


In [37]:
del my_string

In [38]:
print(my_string)

NameError: name 'my_string' is not defined

# Lists

In [39]:
# Python List

mylist1=[1,3,5,4,2]

mylist2 = [1, 4.2, "python" ,4.2]

print(mylist1)
print(mylist2)
print(type(mylist2))

[1, 3, 5, 4, 2]
[1, 4.2, 'python', 4.2]
<class 'list'>


In [40]:
# use of slicing operator
a = [10,20,30,40,50,60,70,80]

print(a[2])

print(a[0:3])

print(a[5:])
print(a[2],a[5])


30
[10, 20, 30]
[60, 70, 80]
30 60


In [41]:
#lists are mutable (Mutable = Can be modified i.e. add/remove/update after initialization) 
#replacing an element on the basis of index number
a[3]="abc"
print(a)

[10, 20, 30, 'abc', 50, 60, 70, 80]


In [99]:
#appending multiple elements
my_list=[1,3,6,9]

my_new_list=[4,5,6,7,8]

my_list.append("xyz")
my_list.extend(my_new_list)

print(my_list)

[1, 3, 6, 9, 'xyz', 4, 5, 6, 7, 8]


In [100]:
my_list.insert(4,"abc")
print(my_list)

[1, 3, 6, 9, 'abc', 'xyz', 4, 5, 6, 7, 8]


In [101]:
my_list.remove(6)
print(my_list)

[1, 3, 9, 'abc', 'xyz', 4, 5, 6, 7, 8]


In [45]:
del my_list[2]
my_list

[1, 3, 'abc', 'xyz', 4, 5, 6, 7, 8]

# Tuples

In [60]:
a = (5,'python',[1,"alex",3], 27.9,5)
print(a)
print(type(a))
print(a[2][1][3])


(5, 'python', [1, 'alex', 3], 27.9, 5)
<class 'tuple'>
x


In [47]:
list1=[1,2,3]
tuple1=tuple(list1)
print(tuple1)

(1, 2, 3)


In [61]:
#tuple is immutable
#a[2]=0

del a


# Sets

In [7]:
my_set = {1,2.0,3,4,3,2,10,"alex",38,72,16}
print(my_set)

{1, 2.0, 3, 4, 38, 'alex', 72, 10, 16}


In [ ]:
#my_set[3]

In [10]:
#Adding elements
my_set = {1,3}
print(my_set)

my_set.add(8)
print(my_set)

my_set.update([6,8,1,4,2])
print(my_set)

#deleting elements
my_set.remove(6)
print(my_set)



{1, 3}
{8, 1, 3}
{1, 2, 3, 4, 6, 8}
{1, 2, 3, 4, 8}


In [57]:
myset = {1,3}
myset.update((5,6,7))
print(myset)

{1, 3, 5, 6, 7}


In [1]:
#Union and intersection

A = [1, 2, 3, 4, 5,9]
B = (4, 5, 6, 7, 8,10)
print(type(A))
setA=set(A)
setB=set(B)

print(setA | setB)
print(setA.union(setB))

print(setA & setB)
print(setA.intersection(setB))

print(setA-setB)
print(setB-setA)

<class 'list'>
{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
{4, 5}
{4, 5}
{1, 2, 3, 9}
{8, 10, 6, 7}


In [103]:
A = [1, 2, 3, 4, 5,9]
B = (4, 5, 6, 7, 8,10)

In [105]:
setA=set(A)
setB=set(B)
print(setA, setB)

{1, 2, 3, 4, 5, 9} {4, 5, 6, 7, 8, 10}


# Dictionaries

In [51]:
# Creating a dictionary
my_d1 = {1: 'A', "B": 2}
print(my_d1)

my_d2 = {"name": ("John","Priya","Alex"), "ID": [2,4], "Marks":[34,45,38],"Marks":[47,45,32]}
print(my_d2)
print(my_d2["name"])
print(my_d2["name"][0],my_d2["ID"][0],my_d2["Marks"][0])
print(my_d1[1])
print(my_d2[0])

{1: 'A', 'B': 2}
{'name': ('John', 'Priya', 'Alex'), 'ID': [2, 4], 'Marks': [47, 45, 32]}
('John', 'Priya', 'Alex')
John 2 47
A


KeyError: 0

In [52]:
my_d={"Name":"Priya","age":[12,27,30]}
my_d['age'][1] = 28
print(my_d)

my_d['address'] = ['Mumbai','Pune']
print(my_d)

{'Name': 'Priya', 'age': [12, 28, 30]}
{'Name': 'Priya', 'age': [12, 28, 30], 'address': ['Mumbai', 'Pune']}


In [53]:
del my_d["age"][1]
print(my_d)

{'Name': 'Priya', 'age': [12, 30], 'address': ['Mumbai', 'Pune']}


In [54]:
my_d.values()

dict_values(['Priya', [12, 30], ['Mumbai', 'Pune']])

In [55]:
my_d.keys()

dict_keys(['Name', 'age', 'address'])

In [23]:
import numpy as np
array_t= np.array({"A":1,"B":2,"C":3})
array_t

array({'A': 1, 'B': 2, 'C': 3}, dtype=object)

# NumPy

## Introduction

- NumPy is a general-purpose array-processing package
- Travis Oliphant First Released in 1995 (Released as __Numeric__; Changed to NumPy in 2006). It is written in Python and C
- NumPy is cross-platform and BSD-licensed. Often used with packages such as Matplotlib (plotting library) and SciPy (Scientific Python). Sometimes it is seen as an alternative to MATLAB. The term ‘Numpy’ is a portmanteau of the words ‘NUMerical’ and ‘PYthon
- It is a library that allows end-users to create **high-performance multidimensional array objects** and manipulate these arrays (objects)
- NumPy provides a gamut of high-level functions for mathematical and logical operations, Fourier transforms, array shape manipulations, linear algebra operations, random number generation, etc.

## Numpy Installation

Once you have installed `pip`, i.e., the default python package manager; installing numpy is straightforward.

`pip install numpy`

## Numpy Import

Conventionally, numpy is imported as `np` as shown below

In [24]:
import numpy as np
print(np.__version__)    # Check the numpy version

1.19.1


## Basic Usage

In [25]:
# Create a 3 x 3 array, with all elements initialized to 1. Default data type for array is float.
b = np.ones((3, 3))
print(b)
type(b)    # print datatype of b
b.dtype    # print datatype of elements in b

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


dtype('float64')

In [26]:
# Modify the data type of array elements
c = np.ones((3, 3), dtype=int)
print(c)
type(c)
c.dtype

[[1 1 1]
 [1 1 1]
 [1 1 1]]


dtype('int32')

In [27]:
d = np.array([11 + 12j, 13 + 14j, 15 + 16j])    # numpy array with complex data type
d.dtype

dtype('complex128')

In [28]:
e = np.array([False, True, True, False, False, True])    # numpy array with boolean data type 
e.dtype

dtype('bool')

In [29]:
f = np.array(['Welcome', 'To', 'Numpy'])
f.dtype    # Unicode string of 7 characters

dtype('<U7')

In [30]:
len(f)    # get the length of the array

3

In [33]:
# Shortcut to create an array of numbers
ar = np.arange(5)
print(ar)
ar = np.arange(10,2,-1)
ar

[0 1 2 3 4]


array([10,  9,  8,  7,  6,  5,  4,  3])

In [40]:
# Indexing on 1-D array - This is similar to Python lists
ar[1], ar[3], ar[-1]

(9, 7, 3)

In [41]:
# Arrays are assigned by reference

a = np.array([10, 11, 12, 13]) # create array
print(a)       # print a's value
print(type(a)) # type of variable a 
print(id(a))

b = a    # reference assignment
print(id(b))
b[0] = 20
print(a[0])

[10 11 12 13]
<class 'numpy.ndarray'>
2329053741184
2329053741184
20


In [42]:
a = np.array([10, 11, 12, 13]) # create array
print(a)       # print a's value
print(type(a)) # type of variable a 
print(id(a))

b = a.copy()    #  assignment
print(id(b))
b[0] = 20
print(a[0])

[10 11 12 13]
<class 'numpy.ndarray'>
2329053732496
2329053730576
10


In [39]:
a=np.array([(1,2,3),(4,5,6),(7,8,9)])
print(a)
print(a.ndim)
print(a.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)


In [38]:
a=np.array([((1,2,3),(4,5,6),(7,8,9)),((1,2,3),(4,5,6),(7,8,9))])
print(a)
print(a.ndim)
print(a.shape)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
3
(2, 3, 3)


## Indexing and slicing

Indexes are tuples of numbers

In [48]:
a = np.diag(np.arange(3))   # create a 3 by 3 array with diagonal elements set to 0, 1, 2
print(a)
print(a[1, 1])
# Indexing starts with 0. Here we are slicing one element in the second row and second column. We used a tuple 1, 1
a[2][2]

[[0 0 0]
 [0 1 0]
 [0 0 2]]
1


2

In [49]:
a[2, 1] = 10 # Update array element
a

array([[ 0,  0,  0],
       [ 0,  1,  0],
       [ 0, 10,  2]])

In [50]:
print(a[1:, 0:2])  # We can use slicing concepts for all the dimensions!

[[ 0  1]
 [ 0 10]]


In [51]:
ar = np.arange(10)
print(ar)
ar[:4]    # Slice, starting from zero and ending at three

[0 1 2 3 4 5 6 7 8 9]


array([0, 1, 2, 3])

In [52]:
ar[::2]    # Slice every second element, starting from 0

array([0, 2, 4, 6, 8])

## Transpose

In [59]:
import numpy as np
help(np.transpose)

Help on function transpose in module numpy:

transpose(a, axes=None)
    Reverse or permute the axes of an array; returns the modified array.
    
    For an array a with two axes, transpose(a) gives the matrix transpose.
    
    Parameters
    ----------
    a : array_like
        Input array.
    axes : tuple or list of ints, optional
        If specified, it must be a tuple or list which contains a permutation of
        [0,1,..,N-1] where N is the number of axes of a.  The i'th axis of the
        returned array will correspond to the axis numbered ``axes[i]`` of the
        input.  If not specified, defaults to ``range(a.ndim)[::-1]``, which
        reverses the order of the axes.
    
    Returns
    -------
    p : ndarray
        `a` with its axes permuted.  A view is returned whenever
        possible.
    
    See Also
    --------
    moveaxis
    argsort
    
    Notes
    -----
    Use `transpose(a, argsort(axes))` to invert the transposition of tensors
    when using the

In [53]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Array shape:", arr.shape)
print(arr)
arr_transp = np.transpose(arr)
print("Transpose array shape:", arr_transp.shape)
print(arr_transp)
# + np.transpose([np.arange(0, 51, 10)])

Array shape: (2, 3)
[[1 2 3]
 [4 5 6]]
Transpose array shape: (3, 2)
[[1 4]
 [2 5]
 [3 6]]


## Updating Array Values

In [54]:
arr[1][1] = 2
print(arr)    # value 5 is updated by 2

arr_transp[1, 1] = 2  # value 5 updated by 2
print(arr_transp)

[[1 2 3]
 [4 2 6]]
[[1 4]
 [2 2]
 [3 6]]


## Total Number of Elements in the Array

In [55]:
import numpy as np 
help(np.size)

Help on function size in module numpy:

size(a, axis=None)
    Return the number of elements along a given axis.
    
    Parameters
    ----------
    a : array_like
        Input data.
    axis : int, optional
        Axis along which the elements are counted.  By default, give
        the total number of elements.
    
    Returns
    -------
    element_count : int
        Number of elements along the specified axis.
    
    See Also
    --------
    shape : dimensions of array
    ndarray.shape : dimensions of array
    ndarray.size : number of elements in array
    
    Examples
    --------
    >>> a = np.array([[1,2,3],[4,5,6]])
    >>> np.size(a)
    6
    >>> np.size(a,1)
    3
    >>> np.size(a,0)
    2



In [56]:
arr.size 

6

## Array of Random Numbers

In [58]:
import numpy as np
help(np.random.random)

Help on built-in function random:

random(...) method of numpy.random.mtrand.RandomState instance
    random(size=None)
    
    Return random floats in the half-open interval [0.0, 1.0). Alias for
    `random_sample` to ease forward-porting to the new random API.



In [57]:
nr = np.random.random((3, 3)) # 2 dimensional array of 3 rows and 3 columns with random numbers 
# Elements in array are randomly generated using the random function.
print(nr)      

[[0.54835933 0.0616952  0.0993219 ]
 [0.8626579  0.26225547 0.04316864]
 [0.84699857 0.0921451  0.74802806]]


## Array Functions

### `np.ones()`

Returns a new array of given shape and data type, where all the elements are set to 1.

`ones(shape, dtype=None, order='C')`

The shape is an int or tuple of ints to define the size of the array. If we just specify an int variable, a one-dimensional array will be returned. For a tuple of ints, the array of given shape will be returned.<br>
The dtype is an optional parameter with default value as a float. It’s used to specify the data type of the array, for example, int. <br>
The order defines the whether to store multi-dimensional array in row-major (C-style) or column-major (Fortran-style) order in memory.

In [62]:
help(np.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C')
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of ones with the given shape, dtype, and order.
    
    See Also
    --------
    ones_like : Return an array of ones with shape and type of input.
    empty : Return a new uninitialized array.
    zeros : Return a new array setting values to zero.
    full : Return a new array of given shape filled with value.
    
    
    Examples
    --------
   

In [63]:
c = np.ones((3, 2))
print(c)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


### `np.zeros()`

It is identical to `np.ones()`, except that all the elements are initialized to zero.

In [64]:
import numpy as np
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C')
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of zeros with the given shape, dtype, and order.
    
    See Also
    --------
    zeros_like : Return an array of zeros with shape and type of input.
    empty : Return a new uninitialized array.
    ones : Return a new array setting values to one.
    full : Return a new array of given shape filled with value.
    
 

In [65]:
d = np.zeros((2, 3))
print(d)

[[0. 0. 0.]
 [0. 0. 0.]]


### `np.eye()`

Returns an array where all the elements are equal to zero, except diagonal elements that are initialized to 1.

In [ ]:
import numpy as np
help(np.eye)

In [66]:
e = np.eye((3))  # This creates the popularly known Identity Matrix!
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [43]:
# Different dimensions of arrays created with np.eye
print(np.eye(5))
print()
print(np.eye(2,3))
print()
print(np.eye(3,3))
print()
print(np.eye(4, k=-3))# k is the dimension
print()
print(np.eye(5, k=2))
print()
print(np.eye(2, 3))
print()
print(np.eye(5, dtype=int))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]]

[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[[1. 0. 0.]
 [0. 1. 0.]]

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


### `full()`
Returns a new array with the same shape and type as a given, filled with the fill_value.
    
Syntax:

`full(shape, fill_value, dtype = None, order = 'C')`

In [ ]:
help(np.full)

In [44]:
e = np.full((5, 4), 7) # Matrix of constant numbers
print(e)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


### `np.linspace()`

Returns number spaces evenly w.r.t the given interval start and stop. This functions is similar to arange but instead of step size it uses a sample number.

Syntax:

`numpy.linspace(start, stop, num = 50, endpoint = True, retstep = False, dtype = None)

In [ ]:
import numpy as np 
help(np.linspace)

In [ ]:
f = np.linspace(1, 10, 4) # Generate 4 equally spaced values between 1 and 10
print(f)

In [ ]:
# Sample other variations of linspace
print(np.linspace(1, 2, retstep=True))
print()
print(np.linspace(1, 100, num=5, retstep=True))
print()
a = np.linspace(1, 100, num=5, endpoint=False, retstep=True)
print(a)
print(a[0][0])
np.linspace(1, 100, num=5, retstep=True)
np.linspace(1, 100, num=5, dtype=int)

In [61]:
a =[1, np.NaN, 3]
print(np.array(a))

[ 1. nan  3.]


## Some interesting numpy functions

### Math functions
numpy has a fairly big set of functions to for mathematical operations

In [78]:
# standard math functions, like mean, standard deviations, max, min, etc. 
# are all available
a = np.array([10, 8, 9])

print(a)

print('Mean: ', np.mean(a))
print('Standard deviation: ', np.std(a))
print('Max: ', np.max(a))
print('Min: ', np.min(a))
print('Index Max: ', np.argmax(a))
print('Ix Min: ', np.argmin(a))


[10  8  9]
Mean:  9.0
Standard deviation:  0.816496580927726
Max:  10
Min:  8
Index Max:  0
Ix Min:  1


In [77]:
a =[1,2,1]
var = 1
b=[]
count=0
for i in a:
    if(i==var):
        b.append(count)
    count=count + 1
    print(b)       


[0]
[0]
[0, 2]


### Inserting and deleting elements

numpy are blocks of memory with a different layout than the list. For this reason it's not possible to append and element like a list, thoug similar functions are provided

In [107]:
a = np.array([1, 2, 3])

b = np.append(a, 3); print(b) # insert the number 3 at the end
c = np.insert(a, 2, 12); print(c)  # insert the value 12 at index 2
d = np.delete(a, 1); print(d) # delete the value at index 1

[1 2 3 3]
[ 1  2 12  3]
[1 3]


In [91]:
#math functions

a=np.array([(1,0,3),(3,4,5)])
print(a)

print(np.sqrt(a))
print()

print(np.std(a))
print()

print(np.log(a))
print()

b=np.sqrt(a)
print(b.round(2))

print(np.sqrt(a).round(2))

[[1 0 3]
 [3 4 5]]
[[1.         0.         1.73205081]
 [1.73205081 2.         2.23606798]]

1.699673171197595

[[0.               -inf 1.09861229]
 [1.09861229 1.38629436 1.60943791]]

[[1.   0.   1.73]
 [1.73 2.   2.24]]
[[1.   0.   1.73]
 [1.73 2.   2.24]]


C:\Users\DILJYOT\anaconda3\lib\site-packages\ipykernel_launcher.py:12: RuntimeWarning: divide by zero encountered in log
  if sys.path[0] == '':


In [ ]:
?np.sqrt

In [45]:
x= np.array([(1,2),(3,4)])
y= np.array([(5,6),(3,4)])
print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]
 [3 4]]


In [46]:
print(x+y)
print(x-y)
print(x*y)# element to element multiplication
print(x/y)
print(x%y)
print(x@y)# Matrix Multiplication
#print(np.dot(x,y))
#print(np.add(x,y))

#np.add(), np.subtract(), np.multiply(), np.divide(), np.remainder()

[[6 8]
 [6 8]]
[[-4 -4]
 [ 0  0]]
[[ 5 12]
 [ 9 16]]
[[0.2        0.33333333]
 [1.         1.        ]]
[[1 2]
 [0 0]]
[[11 14]
 [27 34]]


In [85]:
#arrays are mutable
x= np.array([(1,2,3),(3,4,5)])
x[0,1]=7
print(x)

[[1 7 3]
 [3 4 5]]


In [86]:
# ravel() functions returns contiguous flattened array
# (1D array with all the input-array elements and with the same type as it)

print(x)

y=x.ravel()
print(y)

[[1 7 3]
 [3 4 5]]
[1 7 3 3 4 5]


In [87]:
y.reshape((2,3))

array([[1, 7, 3],
       [3, 4, 5]])

In [88]:
z=np.array([1,2,3,4,5,6,7,8])
z.ndim

1

In [89]:
z.reshape((2,4))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [90]:
list = [[1,2,3],[4,5,6]]
print(list)

[[1, 2, 3], [4, 5, 6]]


In [93]:
a={"a":1,"b":2,"c":3}
b=np.array(a)
b

array({'a': 1, 'b': 2, 'c': 3}, dtype=object)

In [96]:
b[0]

IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed

In [98]:
b.ndim

0